language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

script:
  - npm install

deploy:
  provider: heroku
  api_key: 2eb426fe-bbac-4700-a545-e0ca3fcf9baf
  app: node-express-routing
  on:
    all_branches: true
  strategy: git
  